sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile."
  - docker build -t 5dhumat/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true 5dhumat/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-548811523680"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY